volumes:
  mongo_data:
services:
  pwkeeper:
    build: .
    pull_policy: build
    image: pwkeeper
    ports:
      - 3200:3200
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db